"""
Alerts management endpoints for AI Risk Manager.

Provides CRUD operations for alerts generated by the fraud detection pipeline.
"""

import json
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from sqlalchemy import func

from src.database import get_db_session
from src.models_db import Alert, Transaction
from src.utils import logger

router = APIRouter()


# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------

class AlertOut(BaseModel):
    """Alert record returned by the API."""
    id: int
    transaction_id: str
    risk_score: int
    risk_level: str
    reason: Optional[List[str]] = None
    status: str
    reviewed_by: Optional[str] = None
    reviewed_at: Optional[str] = None
    created_at: str
    # Joined transaction info
    amount: Optional[float] = None
    merchant_category: Optional[str] = None


class AlertStatusUpdate(BaseModel):
    """Request to update an alert's status."""
    status: str = Field(..., description="New status: REVIEWED / CONFIRMED_FRAUD / FALSE_POSITIVE")
    reviewed_by: Optional[str] = Field(None, description="Analyst identifier")


class AlertStats(BaseModel):
    """Aggregated alert statistics."""
    total: int
    open: int
    reviewed: int
    confirmed_fraud: int
    false_positive: int
    high_risk: int
    medium_risk: int


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.get(
    "/alerts",
    summary="List alerts with optional filtering",
    tags=["Alerts"],
)
def get_alerts(
    status: Optional[str] = None,
    risk_level: Optional[str] = None,
    limit: int = 100,
    offset: int = 0,
) -> Dict[str, Any]:
    """Return alerts with optional status and risk_level filters."""
    limit = min(limit, 500)
    try:
        with get_db_session() as session:
            query = session.query(Alert)

            if status:
                query = query.filter(Alert.status == status.upper())
            if risk_level:
                query = query.filter(Alert.risk_level == risk_level.upper())

            total = query.count()
            rows = (
                query.order_by(Alert.created_at.desc())
                .offset(offset)
                .limit(limit)
                .all()
            )

            results = []
            for alert in rows:
                # Parse reason JSON
                reason_list = None
                if alert.reason:
                    try:
                        reason_list = json.loads(alert.reason)
                    except (json.JSONDecodeError, TypeError):
                        reason_list = [alert.reason]

                # Get transaction info
                txn = (
                    session.query(Transaction)
                    .filter(Transaction.transaction_id == alert.transaction_id)
                    .first()
                )

                results.append(
                    AlertOut(
                        id=alert.id,
                        transaction_id=alert.transaction_id,
                        risk_score=alert.risk_score,
                        risk_level=alert.risk_level,
                        reason=reason_list,
                        status=alert.status,
                        reviewed_by=alert.reviewed_by,
                        reviewed_at=alert.reviewed_at.isoformat() if alert.reviewed_at else None,
                        created_at=alert.created_at.isoformat() if alert.created_at else "",
                        amount=txn.amount if txn else None,
                        merchant_category=txn.merchant_category if txn else None,
                    ).model_dump()
                )

            return {"alerts": results, "total": total, "limit": limit, "offset": offset}

    except Exception as exc:
        logger.error(f"Failed to fetch alerts: {exc}")
        raise HTTPException(status_code=500, detail="Failed to retrieve alerts")


@router.get(
    "/alerts/stats",
    response_model=AlertStats,
    summary="Get alert statistics",
    tags=["Alerts"],
)
def get_alert_stats() -> AlertStats:
    """Return aggregated alert statistics."""
    try:
        with get_db_session() as session:
            total = session.query(func.count(Alert.id)).scalar() or 0
            open_count = session.query(func.count(Alert.id)).filter(
                Alert.status == "OPEN"
            ).scalar() or 0
            reviewed = session.query(func.count(Alert.id)).filter(
                Alert.status == "REVIEWED"
            ).scalar() or 0
            confirmed = session.query(func.count(Alert.id)).filter(
                Alert.status == "CONFIRMED_FRAUD"
            ).scalar() or 0
            false_pos = session.query(func.count(Alert.id)).filter(
                Alert.status == "FALSE_POSITIVE"
            ).scalar() or 0
            high = session.query(func.count(Alert.id)).filter(
                Alert.risk_level == "HIGH"
            ).scalar() or 0
            medium = session.query(func.count(Alert.id)).filter(
                Alert.risk_level == "MEDIUM"
            ).scalar() or 0

            return AlertStats(
                total=total,
                open=open_count,
                reviewed=reviewed,
                confirmed_fraud=confirmed,
                false_positive=false_pos,
                high_risk=high,
                medium_risk=medium,
            )
    except Exception as exc:
        logger.error(f"Failed to compute alert stats: {exc}")
        raise HTTPException(status_code=500, detail="Failed to compute alert statistics")


@router.put(
    "/alerts/{alert_id}",
    summary="Update alert status (review, confirm fraud, or false positive)",
    tags=["Alerts"],
)
def update_alert_status(alert_id: int, payload: AlertStatusUpdate) -> Dict[str, Any]:
    """Update an alert's status to REVIEWED, CONFIRMED_FRAUD, or FALSE_POSITIVE."""
    valid_statuses = {"OPEN", "REVIEWED", "CONFIRMED_FRAUD", "FALSE_POSITIVE"}
    if payload.status.upper() not in valid_statuses:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid status '{payload.status}'. Must be one of: {sorted(valid_statuses)}",
        )

    try:
        with get_db_session() as session:
            alert = session.query(Alert).filter(Alert.id == alert_id).first()
            if not alert:
                raise HTTPException(status_code=404, detail=f"Alert {alert_id} not found")

            alert.status = payload.status.upper()
            alert.reviewed_by = payload.reviewed_by
            alert.reviewed_at = datetime.now(timezone.utc)

            return {
                "id": alert.id,
                "transaction_id": alert.transaction_id,
                "status": alert.status,
                "reviewed_by": alert.reviewed_by,
                "reviewed_at": alert.reviewed_at.isoformat(),
                "message": f"Alert status updated to {alert.status}",
            }
    except HTTPException:
        raise
    except Exception as exc:
        logger.error(f"Failed to update alert {alert_id}: {exc}")
        raise HTTPException(status_code=500, detail="Failed to update alert")
